#include "Tileset.h"


CUINT TS_EMPTY = 0;
CUINT TS_FOUNTAIN_BLOOD1 = 1;
CUINT TS_FOUNTAIN_BLOOD2 = 2;
CUINT TS_FOUNTAIN_WATER1 = 3;
CUINT TS_FOUNTAIN_WATER2 = 4;
CUINT TS_COOKIE = 5;
CUINT TS_CHEST1 = 6;
CUINT TS_CHEST2 = 7;
CUINT TS_CHEST2_OPENED = 8;
CUINT TS_FOUNTAIN_EMPTY = 9;
CUINT TS_BOX_WOODEN = 10;
CUINT TS_DEBRIS_GREEN1 = 11;
CUINT TS_DEBRIS_GREEN2 = 12;
CUINT TS_DEBRIS_GREEN3 = 13;
CUINT TS_DEBRIS_GREEN4 = 14;
CUINT TS_COFFIN_MUMMY = 15;
CUINT TS_FOUNTAIN_MAGIC_WATER1 = 16;
CUINT TS_FOUNTAIN_MAGIC_WATER2 = 17;
CUINT TS_EMPTY_BLACK = 18;
CUINT TS_POLE_MAGIC_PINK = 19;
CUINT TS_ALTAR_DESTROYED = 20;
CUINT TS_STATUE_EMPTY = 21;
CUINT TS_STATUE_WARRIOR = 22;
CUINT TS_STATUE_TURTLE = 23;
CUINT TS_STATUE_TURTLE_CLOCK1 = 24;
CUINT TS_STATUE_TURTLE_CLOCK2 = 25;
CUINT TS_STATUE_TURTLE_CLOCK3 = 26;
CUINT TS_STATUE_TURTLE_CLOCK4 = 27;
CUINT TS_STATUE_TURTLE_CLOCK5 = 28;
CUINT TS_STATUE_TURTLE_CLOCK6 = 29;
CUINT TS_STATUE_TURTLE_CLOCK7 = 30;
CUINT TS_STATUE_TURTLE_CLOCK8 = 31;
CUINT TS_STATUE_POT = 32;
CUINT TS_STATUE_VERY_OLD = 33;
CUINT TS_STATUE_GREEN1 = 34;
CUINT TS_STATUE_GREEN2 = 35;
CUINT TS_STATUE_GREEN3 = 36;
CUINT TS_STATUE_GREEN4 = 37;
CUINT TS_STATUE_GREEN5 = 38;
CUINT TS_STATUE_GREEN6 = 39;
CUINT TS_STATUE_GREEN7 = 40;
CUINT TS_STATUE_GREEN8 = 41;
CUINT TS_STATUE_GREEN9 = 42;
CUINT TS_STATUE_GREEN10 = 43;
CUINT TS_STATUE_GREEN11 = 44;
CUINT TS_STATUE_SKULLS = 45;
CUINT TS_STATUE_VIOLET_HOLE = 46;
CUINT TS_STATUE_FLAME1 = 47;
CUINT TS_STATUE_FLAME2 = 48;
CUINT TS_STATUE_FLAME3 = 49;
CUINT TS_STATUE_FLAME4 = 50;
CUINT TS_STATUE_FLAME5 = 51;
CUINT TS_STATUE_FLAME6 = 52;
CUINT TS_STATUE_FLAME7 = 53;
CUINT TS_STATUE_FLAME8 = 54;



