#pragma once


typedef const unsigned int CUINT;


extern CUINT TS_EMPTY;
extern CUINT TS_FOUNTAIN_BLOOD1;
extern CUINT TS_FOUNTAIN_BLOOD2;
extern CUINT TS_FOUNTAIN_WATER1;
extern CUINT TS_FOUNTAIN_WATER2;
extern CUINT TS_COOKIE;
extern CUINT TS_CHEST1;
extern CUINT TS_CHEST2;
extern CUINT TS_CHEST2_OPENED;
extern CUINT TS_FOUNTAIN_EMPTY;
extern CUINT TS_BOX_WOODEN;
extern CUINT TS_DEBRIS_GREEN1;
extern CUINT TS_DEBRIS_GREEN2;
extern CUINT TS_DEBRIS_GREEN3;
extern CUINT TS_DEBRIS_GREEN4;
extern CUINT TS_COFFIN_MUMMY;
extern CUINT TS_FOUNTAIN_MAGIC_WATER1;
extern CUINT TS_FOUNTAIN_MAGIC_WATER2;
extern CUINT TS_EMPTY_BLACK;
extern CUINT TS_POLE_MAGIC_PINK;
extern CUINT TS_ALTAR_DESTROYED;
extern CUINT TS_STATUE_EMPTY;
extern CUINT TS_STATUE_WARRIOR;
extern CUINT TS_STATUS_TURTLE;
extern CUINT TS_STATUS_TURTLE_CLOCK1;
extern CUINT TS_STATUS_TURTLE_CLOCK2;
extern CUINT TS_STATUS_TURTLE_CLOCK3;
extern CUINT TS_STATUS_TURTLE_CLOCK4;
extern CUINT TS_STATUS_TURTLE_CLOCK5;
extern CUINT TS_STATUS_TURTLE_CLOCK6;
extern CUINT TS_STATUS_TURTLE_CLOCK7;
extern CUINT TS_STATUS_TURTLE_CLOCK8;
extern CUINT TS_STATUE_POT;
extern CUINT TS_STATUE_VERY_OLD;
extern CUINT TS_STATUE_GREEN1;
extern CUINT TS_STATUE_GREEN2;
extern CUINT TS_STATUE_GREEN3;
extern CUINT TS_STATUE_GREEN4;
extern CUINT TS_STATUE_GREEN5;
extern CUINT TS_STATUE_GREEN6;
extern CUINT TS_STATUE_GREEN7;
extern CUINT TS_STATUE_GREEN8;
extern CUINT TS_STATUE_GREEN9;
extern CUINT TS_STATUE_GREEN10;
extern CUINT TS_STATUE_GREEN11;
extern CUINT TS_STATUE_SKULLS;
extern CUINT TS_STATUE_VIOLET_HOLE;
extern CUINT TS_STATUE_FLAME1;
extern CUINT TS_STATUE_FLAME2;
extern CUINT TS_STATUE_FLAME3;
extern CUINT TS_STATUE_FLAME4;
extern CUINT TS_STATUE_FLAME5;
extern CUINT TS_STATUE_FLAME6;
extern CUINT TS_STATUE_FLAME7;
extern CUINT TS_STATUE_FLAME8;








